# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/admin_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminUsuarios(object):
    def setupUi(self, AdminUsuarios):
        AdminUsuarios.setObjectName("AdminUsuarios")
        AdminUsuarios.resize(695, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdminUsuarios)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tablaUsuarios = QtWidgets.QTableWidget(AdminUsuarios)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tablaUsuarios.setFont(font)
        self.tablaUsuarios.setColumnCount(4)
        self.tablaUsuarios.setObjectName("tablaUsuarios")
        self.tablaUsuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tablaUsuarios)
        self.groupBox = QtWidgets.QGroupBox(AdminUsuarios)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Rol = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Rol.setFont(font)
        self.Rol.setObjectName("Rol")
        self.Rol.addItem("")
        self.Rol.addItem("")
        self.Rol.addItem("")
        self.horizontalLayout.addWidget(self.Rol)
        self.btnActualizar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnActualizar.setFont(font)
        self.btnActualizar.setObjectName("btnActualizar")
        self.horizontalLayout.addWidget(self.btnActualizar)
        self.btnAbrirCrearUsuario = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnAbrirCrearUsuario.setFont(font)
        self.btnAbrirCrearUsuario.setObjectName("btnAbrirCrearUsuario")
        self.horizontalLayout.addWidget(self.btnAbrirCrearUsuario)
        self.Eliminar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Eliminar.setFont(font)
        self.Eliminar.setObjectName("Eliminar")
        self.horizontalLayout.addWidget(self.Eliminar)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(AdminUsuarios)
        QtCore.QMetaObject.connectSlotsByName(AdminUsuarios)

    def retranslateUi(self, AdminUsuarios):
        _translate = QtCore.QCoreApplication.translate
        AdminUsuarios.setWindowTitle(_translate("AdminUsuarios", "Dialog"))
        item = self.tablaUsuarios.horizontalHeaderItem(0)
        item.setText(_translate("AdminUsuarios", "ID"))
        item = self.tablaUsuarios.horizontalHeaderItem(1)
        item.setText(_translate("AdminUsuarios", "Nombre"))
        item = self.tablaUsuarios.horizontalHeaderItem(2)
        item.setText(_translate("AdminUsuarios", "Email"))
        item = self.tablaUsuarios.horizontalHeaderItem(3)
        item.setText(_translate("AdminUsuarios", "Rol"))
        self.Rol.setItemText(0, _translate("AdminUsuarios", "Cliente"))
        self.Rol.setItemText(1, _translate("AdminUsuarios", "Empleado"))
        self.Rol.setItemText(2, _translate("AdminUsuarios", "Administrador"))
        self.btnActualizar.setText(_translate("AdminUsuarios", "Actualizar"))
        self.btnAbrirCrearUsuario.setText(_translate("AdminUsuarios", "Añadir "))
        self.Eliminar.setText(_translate("AdminUsuarios", "Eliminar"))
