# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contenedorCentral(object):
    def setupUi(self, contenedorCentral):
        contenedorCentral.setObjectName("contenedorCentral")
        contenedorCentral.resize(496, 699)
        self.widget = QtWidgets.QWidget(contenedorCentral)
        self.widget.setGeometry(QtCore.QRect(90, 10, 381, 671))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("interfaces\\logoGestionTapas.jpg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.lblNombre = QtWidgets.QLabel(self.widget)
        self.lblNombre.setObjectName("lblNombre")
        self.verticalLayout.addWidget(self.lblNombre)
        self.txtNombre = QtWidgets.QLineEdit(self.widget)
        self.txtNombre.setText("")
        self.txtNombre.setObjectName("txtNombre")
        self.verticalLayout.addWidget(self.txtNombre)
        self.lblemail = QtWidgets.QLabel(self.widget)
        self.lblemail.setObjectName("lblemail")
        self.verticalLayout.addWidget(self.lblemail)
        self.txtEmail = QtWidgets.QLineEdit(self.widget)
        self.txtEmail.setText("")
        self.txtEmail.setObjectName("txtEmail")
        self.verticalLayout.addWidget(self.txtEmail)
        self.lblContrasena = QtWidgets.QLabel(self.widget)
        self.lblContrasena.setObjectName("lblContrasena")
        self.verticalLayout.addWidget(self.lblContrasena)
        self.txtContrasena = QtWidgets.QLineEdit(self.widget)
        self.txtContrasena.setText("")
        self.txtContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContrasena.setObjectName("txtContrasena")
        self.verticalLayout.addWidget(self.txtContrasena)
        self.lblContrasena2 = QtWidgets.QLabel(self.widget)
        self.lblContrasena2.setObjectName("lblContrasena2")
        self.verticalLayout.addWidget(self.lblContrasena2)
        self.txtContrasena2 = QtWidgets.QLineEdit(self.widget)
        self.txtContrasena2.setText("")
        self.txtContrasena2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContrasena2.setObjectName("txtContrasena2")
        self.verticalLayout.addWidget(self.txtContrasena2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboRol = QtWidgets.QComboBox(self.widget)
        self.comboRol.setObjectName("comboRol")
        self.comboRol.addItem("")
        self.comboRol.addItem("")
        self.comboRol.addItem("")
        self.verticalLayout.addWidget(self.comboRol)
        self.btnRegistrarse = QtWidgets.QPushButton(self.widget)
        self.btnRegistrarse.setObjectName("btnRegistrarse")
        self.verticalLayout.addWidget(self.btnRegistrarse)
        self.lblError = QtWidgets.QLabel(self.widget)
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(contenedorCentral)
        QtCore.QMetaObject.connectSlotsByName(contenedorCentral)

    def retranslateUi(self, contenedorCentral):
        _translate = QtCore.QCoreApplication.translate
        contenedorCentral.setWindowTitle(_translate("contenedorCentral", "Dialog"))
        self.lblNombre.setText(_translate("contenedorCentral", "Nombre de usuario:"))
        self.lblemail.setText(_translate("contenedorCentral", "Email:"))
        self.lblContrasena.setText(_translate("contenedorCentral", "Contraseña:"))
        self.lblContrasena2.setText(_translate("contenedorCentral", "Confirmar Contraseña:"))
        self.label.setText(_translate("contenedorCentral", "Rol:"))
        self.comboRol.setItemText(0, _translate("contenedorCentral", "Cliente"))
        self.comboRol.setItemText(1, _translate("contenedorCentral", "admin"))
        self.comboRol.setItemText(2, _translate("contenedorCentral", "empleado"))
        self.btnRegistrarse.setText(_translate("contenedorCentral", "Registrarse"))
