# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/admin_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminUsuarios(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 340)
        self.tablaUsuarios = QtWidgets.QTableWidget(Dialog)
        self.tablaUsuarios.setGeometry(QtCore.QRect(20, 10, 511, 192))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tablaUsuarios.setFont(font)
        self.tablaUsuarios.setColumnCount(4)
        self.tablaUsuarios.setObjectName("tablaUsuarios")
        self.tablaUsuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaUsuarios.setHorizontalHeaderItem(3, item)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 210, 511, 52))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Rol = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Rol.setFont(font)
        self.Rol.setObjectName("Rol")
        self.Rol.addItem("")
        self.Rol.addItem("")
        self.Rol.addItem("")
        self.horizontalLayout.addWidget(self.Rol)
        self.Actualizar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Actualizar.setFont(font)
        self.Actualizar.setObjectName("Actualizar\n""")
        self.horizontalLayout.addWidget(self.Actualizar)
        self.btnAbrirCrearUsuario = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnAbrirCrearUsuario.setFont(font)
        self.btnAbrirCrearUsuario.setObjectName("btnAbrirCrearUsuario")
        self.horizontalLayout.addWidget(self.btnAbrirCrearUsuario)
        self.Eliminar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Eliminar.setFont(font)
        self.Eliminar.setObjectName("Eliminar")
        self.horizontalLayout.addWidget(self.Eliminar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tablaUsuarios.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tablaUsuarios.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tablaUsuarios.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Email"))
        item = self.tablaUsuarios.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Rol"))
        self.Rol.setItemText(0, _translate("Dialog", "cliente"))
        self.Rol.setItemText(1, _translate("Dialog", "empleado"))
        self.Rol.setItemText(2, _translate("Dialog", "administrador"))
        self.Actualizar.setText(_translate("Dialog", "Actualizar"))
        self.btnAbrirCrearUsuario.setText(_translate("Dialog", "Añadir "))
        self.Eliminar.setText(_translate("Dialog", "Eliminar"))
